language: elixir
elixir:
  - 1.6.6
  - 1.7.4
  - 1.8.0
otp_release:
  - 19.2
  - 20.0
  - 21.0
matrix:
  exclude:
    - elixir: 1.8.0
      otp_release: 19.2

sudo: false
script:
  - MIX_ENV=test mix coveralls.travis
